spring:
  application:
    name: crypto-service
  config:
    import: ${VAULT_CONFIG_IMPORT:vault:///secret/expense-tracker-backend/crypto}
  cloud:
    vault:
      uri: ${VAULT_URI:http://localhost:8200}
      token: ${VAULT_TOKEN:tech-engg-token}
      kv:
        backend: secret
        backend-version: 2

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html

crypto:
  key-id: local-rsa-key-v1
  hmac-secret: ${CRYPTO_HMAC_SECRET}